groups:
  - name: service_alerts
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Usługa {{ $labels.job }} nie działa"
          description: "Usługa {{ $labels.instance }} jest niedostępna."

      - alert: HighPaymentErrors
        expr: 'sum(rate(payments_processed_total{status="failed"}[5m])) > 1'
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Wysoka liczba nieudanych płatności"

      - alert: HighHttp5xxErrors
        expr: sum(rate(http_server_requests_seconds_count{status=~"5.*"}[5m])) by (job) > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Wysoka liczba błędów HTTP 5xx w usłudze {{ $labels.job }}"
          description: "Usługa {{ $labels.job }} zgłasza błędy serwera (5xx)."

      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le, job)) > 1.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Wysoka latencja (p95 > 1.5s) w usłudze {{ $labels.job }}"
          description: "95% żądań do {{ $labels.job }} trwa dłużej niż 1.5 sekundy."

      - alert: JvmHeapUsageHigh
        expr: sum(jvm_memory_used_bytes{area="heap"}) by (job) / sum(jvm_memory_max_bytes{area="heap"}) by (job) > 0.8
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Wysokie zużycie pamięci JVM (Sterta) w {{ $labels.job }}"
          description: "Usługa {{ $labels.job }} zużywa ponad 80% dostępnej pamięci sterty (heap)."
